package com.furtabs.asylumresources.datagen;

import com.furtabs.asylumresources.block.ModBlocks;
import com.furtabs.asylumresources.util.ModTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.Tags;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagGenerator extends BlockTagsProvider {
    public ModBlockTagGenerator(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper ){
        super(output, lookupProvider, com.furtabs.asylumresources.AsylumRes.MOD_ID, existingFileHelper);
    }

    private static TagKey<Block> tag(String name) {
        return TagKey.create(Registries.BLOCK, ResourceLocation.fromNamespaceAndPath(com.furtabs.asylumresources.AsylumRes.MOD_ID, name));
    }

    public static final TagKey<Block> MINEABLE_WITH_HAMMER = tag("mineable/hammer");

    @Override
    protected void addTags(HolderLookup.Provider pProvider ){
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(
                        ModBlocks.ALUMINUM_BLOCK,
                        ModBlocks.ALUMINUM_ORE,
                        ModBlocks.ANDESITE_ALLOY_BLOCK,
                        ModBlocks.APATITE_BLOCK,
                        ModBlocks.APATITE_ORE,
                        ModBlocks.BRASS_BLOCK,
                        ModBlocks.BRONZE_BLOCK,
                        ModBlocks.CINNABAR_BLOCK,
                        ModBlocks.CINNABAR_ORE,
                        ModBlocks.CONSTANTAN_BLOCK,
                        ModBlocks.DEEPSLATE_ALUMINUM_ORE,
                        ModBlocks.DEEPSLATE_APATITE_ORE,
                        ModBlocks.DEEPSLATE_CINNABAR_ORE,
                        ModBlocks.DEEPSLATE_LEAD_ORE,
                        ModBlocks.DEEPSLATE_NICKEL_ORE,
                        ModBlocks.DEEPSLATE_OSMIUM_ORE,
                        ModBlocks.DEEPSLATE_PLATINUM_ORE,
                        ModBlocks.DEEPSLATE_RUBY_ORE,
                        ModBlocks.DEEPSLATE_SAPPHIRE_ORE,
                        ModBlocks.DEEPSLATE_SILVER_ORE,
                        ModBlocks.DEEPSLATE_TIN_ORE,
                        ModBlocks.DEEPSLATE_URANIUM_ORE,
                        ModBlocks.DEEPSLATE_ZINC_ORE,
                        ModBlocks.ELECTRUM_BLOCK,
                        ModBlocks.ENDERIUM_BLOCK,
                        ModBlocks.GRAPHITE_BLOCK,
                        ModBlocks.IRON_COMPRESSED_BLOCK,
                        ModBlocks.INVAR_BLOCK,
                        ModBlocks.LEAD_BLOCK,
                        ModBlocks.LEAD_ORE,
                        ModBlocks.LUMIUM_BLOCK,
                        ModBlocks.NICKEL_BLOCK,
                        ModBlocks.NICKEL_ORE,
                        ModBlocks.OSMIUM_BLOCK,
                        ModBlocks.OSMIUM_ORE,
                        ModBlocks.PLATINUM_BLOCK,
                        ModBlocks.PLATINUM_ORE,
                        ModBlocks.QUARTZ_ENRICHED_IRON_BLOCK,
                        ModBlocks.RAW_ALUMINUM_BLOCK,
                        ModBlocks.RAW_LEAD_BLOCK,
                        ModBlocks.RAW_NICKEL_BLOCK,
                        ModBlocks.RAW_OSMIUM_BLOCK,
                        ModBlocks.RAW_PLATINUM_BLOCK,
                        ModBlocks.RAW_SILVER_BLOCK,
                        ModBlocks.RAW_TIN_BLOCK,
                        ModBlocks.RAW_URANIUM_BLOCK,
                        ModBlocks.RAW_ZINC_BLOCK,
                        ModBlocks.REFINED_GLOWSTONE_BLOCK,
                        ModBlocks.REFINED_OBSIDIAN_BLOCK,
                        ModBlocks.ROSE_GOLD_BLOCK,
                        ModBlocks.RUBY_BLOCK,
                        ModBlocks.RUBY_ORE,
                        ModBlocks.SAPPHIRE_BLOCK,
                        ModBlocks.SAPPHIRE_ORE,
                        ModBlocks.SIGNALUM_BLOCK,
                        ModBlocks.SILVER_BLOCK,
                        ModBlocks.SILVER_ORE,
                        ModBlocks.STEEL_BLOCK,
                        ModBlocks.TIN_BLOCK,
                        ModBlocks.TIN_ORE,
                        ModBlocks.URANIUM_BLOCK,
                        ModBlocks.URANIUM_ORE,
                        ModBlocks.ZINC_BLOCK,
                        ModBlocks.ZINC_ORE);

        this.tag(MINEABLE_WITH_HAMMER)
                .add(ModBlocks.ALUMINUM_BLOCK,
                        ModBlocks.ALUMINUM_ORE,
                        ModBlocks.ANDESITE_ALLOY_BLOCK,
                        ModBlocks.APATITE_BLOCK,
                        ModBlocks.APATITE_ORE,
                        ModBlocks.BRASS_BLOCK,
                        ModBlocks.BRONZE_BLOCK,
                        ModBlocks.CINNABAR_BLOCK,
                        ModBlocks.CINNABAR_ORE,
                        ModBlocks.CONSTANTAN_BLOCK,
                        ModBlocks.DEEPSLATE_ALUMINUM_ORE,
                        ModBlocks.DEEPSLATE_APATITE_ORE,
                        ModBlocks.DEEPSLATE_CINNABAR_ORE,
                        ModBlocks.DEEPSLATE_LEAD_ORE,
                        ModBlocks.DEEPSLATE_NICKEL_ORE,
                        ModBlocks.DEEPSLATE_OSMIUM_ORE,
                        ModBlocks.DEEPSLATE_PLATINUM_ORE,
                        ModBlocks.DEEPSLATE_RUBY_ORE,
                        ModBlocks.DEEPSLATE_SAPPHIRE_ORE,
                        ModBlocks.DEEPSLATE_SILVER_ORE,
                        ModBlocks.DEEPSLATE_TIN_ORE,
                        ModBlocks.DEEPSLATE_URANIUM_ORE,
                        ModBlocks.DEEPSLATE_ZINC_ORE,
                        ModBlocks.ELECTRUM_BLOCK,
                        ModBlocks.ENDERIUM_BLOCK,
                        ModBlocks.GRAPHITE_BLOCK,
                        ModBlocks.IRON_COMPRESSED_BLOCK,
                        ModBlocks.INVAR_BLOCK,
                        ModBlocks.LEAD_BLOCK,
                        ModBlocks.LEAD_ORE,
                        ModBlocks.LUMIUM_BLOCK,
                        ModBlocks.NICKEL_BLOCK,
                        ModBlocks.NICKEL_ORE,
                        ModBlocks.OSMIUM_BLOCK,
                        ModBlocks.OSMIUM_ORE,
                        ModBlocks.PLATINUM_BLOCK,
                        ModBlocks.PLATINUM_ORE,
                        ModBlocks.QUARTZ_ENRICHED_IRON_BLOCK,
                        ModBlocks.RAW_ALUMINUM_BLOCK,
                        ModBlocks.RAW_LEAD_BLOCK,
                        ModBlocks.RAW_NICKEL_BLOCK,
                        ModBlocks.RAW_OSMIUM_BLOCK,
                        ModBlocks.RAW_PLATINUM_BLOCK,
                        ModBlocks.RAW_SILVER_BLOCK,
                        ModBlocks.RAW_TIN_BLOCK,
                        ModBlocks.RAW_URANIUM_BLOCK,
                        ModBlocks.RAW_ZINC_BLOCK,
                        ModBlocks.REFINED_GLOWSTONE_BLOCK,
                        ModBlocks.REFINED_OBSIDIAN_BLOCK,
                        ModBlocks.ROSE_GOLD_BLOCK,
                        ModBlocks.RUBY_BLOCK,
                        ModBlocks.RUBY_ORE,
                        ModBlocks.SAPPHIRE_BLOCK,
                        ModBlocks.SAPPHIRE_ORE,
                        ModBlocks.SIGNALUM_BLOCK,
                        ModBlocks.SILVER_BLOCK,
                        ModBlocks.SILVER_ORE,
                        ModBlocks.STEEL_BLOCK,
                        ModBlocks.TIN_BLOCK,
                        ModBlocks.TIN_ORE,
                        ModBlocks.URANIUM_BLOCK,
                        ModBlocks.URANIUM_ORE,
                        ModBlocks.ZINC_BLOCK,
                        ModBlocks.ZINC_ORE);

        this.tag(BlockTags.NEEDS_IRON_TOOL)
                .add(ModBlocks.ZINC_ORE,
                        ModBlocks.ZINC_BLOCK,
                        ModBlocks.RAW_ZINC_BLOCK,
                        ModBlocks.DEEPSLATE_ZINC_ORE,
                        ModBlocks.LEAD_ORE,
                        ModBlocks.LEAD_BLOCK,
                        ModBlocks.RAW_LEAD_BLOCK,
                        ModBlocks.DEEPSLATE_LEAD_ORE,
                        ModBlocks.ALUMINUM_BLOCK,
                        ModBlocks.ALUMINUM_ORE,
                        ModBlocks.RAW_ALUMINUM_BLOCK,
                        ModBlocks.DEEPSLATE_ALUMINUM_ORE,
                        ModBlocks.RUBY_ORE,
                        ModBlocks.RUBY_BLOCK,
                        ModBlocks.DEEPSLATE_RUBY_ORE,
                        ModBlocks.SAPPHIRE_BLOCK,
                        ModBlocks.SAPPHIRE_ORE,
                        ModBlocks.DEEPSLATE_SAPPHIRE_ORE,
                        ModBlocks.APATITE_BLOCK,
                        ModBlocks.APATITE_ORE,
                        ModBlocks.DEEPSLATE_APATITE_ORE,
                        ModBlocks.CINNABAR_ORE,
                        ModBlocks.CINNABAR_BLOCK,
                        ModBlocks.DEEPSLATE_CINNABAR_ORE,
                        ModBlocks.BRONZE_BLOCK,
                        ModBlocks.BRASS_BLOCK,
                        ModBlocks.ELECTRUM_BLOCK,
                        ModBlocks.STEEL_BLOCK,
                        ModBlocks.ANDESITE_ALLOY_BLOCK,
                        ModBlocks.ROSE_GOLD_BLOCK,
                        ModBlocks.GRAPHITE_BLOCK);

        this.tag(BlockTags.NEEDS_DIAMOND_TOOL)
                .add(ModBlocks.NICKEL_BLOCK,
                        ModBlocks.NICKEL_ORE,
                        ModBlocks.RAW_NICKEL_BLOCK,
                        ModBlocks.DEEPSLATE_NICKEL_ORE,
                        ModBlocks.URANIUM_ORE,
                        ModBlocks.URANIUM_BLOCK,
                        ModBlocks.RAW_URANIUM_BLOCK,
                        ModBlocks.DEEPSLATE_URANIUM_ORE,
                        ModBlocks.CONSTANTAN_BLOCK,
                        ModBlocks.IRON_COMPRESSED_BLOCK,
                        ModBlocks.INVAR_BLOCK,
                        ModBlocks.SIGNALUM_BLOCK,
                        ModBlocks.ENDERIUM_BLOCK);

        this.tag(BlockTags.NEEDS_STONE_TOOL)
                .add(ModBlocks.SILVER_ORE,
                        ModBlocks.SILVER_BLOCK,
                        ModBlocks.RAW_SILVER_BLOCK,
                        ModBlocks.DEEPSLATE_SILVER_ORE,
                        ModBlocks.TIN_BLOCK,
                        ModBlocks.TIN_ORE,
                        ModBlocks.RAW_TIN_BLOCK,
                        ModBlocks.DEEPSLATE_TIN_ORE);

        this.tag(Tags.Blocks.NEEDS_NETHERITE_TOOL)
                .add(ModBlocks.PLATINUM_BLOCK,
                        ModBlocks.PLATINUM_ORE,
                        ModBlocks.RAW_PLATINUM_BLOCK,
                        ModBlocks.DEEPSLATE_PLATINUM_ORE,
                        ModBlocks.OSMIUM_BLOCK,
                        ModBlocks.OSMIUM_ORE,
                        ModBlocks.RAW_OSMIUM_BLOCK,
                        ModBlocks.DEEPSLATE_OSMIUM_ORE,
                        ModBlocks.REFINED_GLOWSTONE_BLOCK,
                        ModBlocks.REFINED_OBSIDIAN_BLOCK);

        this.tag(ModTags.Blocks.STORAGE_BLOCKS)
                .add(
                        ModBlocks.ANDESITE_ALLOY_BLOCK,
                        ModBlocks.ALUMINUM_BLOCK,
                        ModBlocks.APATITE_BLOCK,
                        ModBlocks.BRASS_BLOCK,
                        ModBlocks.BRONZE_BLOCK,
                        ModBlocks.CINNABAR_BLOCK,
                        ModBlocks.CONSTANTAN_BLOCK,
                        ModBlocks.ELECTRUM_BLOCK,
                        ModBlocks.ENDERIUM_BLOCK,
                        ModBlocks.GRAPHITE_BLOCK,
                        ModBlocks.INVAR_BLOCK,
                        ModBlocks.LEAD_BLOCK,
                        ModBlocks.LUMIUM_BLOCK,
                        ModBlocks.NICKEL_BLOCK,
                        ModBlocks.SIGNALUM_BLOCK,
                        ModBlocks.OSMIUM_BLOCK,
                        ModBlocks.PLATINUM_BLOCK,
                        ModBlocks.QUARTZ_ENRICHED_IRON_BLOCK,
                        ModBlocks.REFINED_GLOWSTONE_BLOCK,
                        ModBlocks.REFINED_OBSIDIAN_BLOCK,
                        ModBlocks.ROSE_GOLD_BLOCK,
                        ModBlocks.RUBY_BLOCK,
                        ModBlocks.SAPPHIRE_BLOCK,
                        ModBlocks.SILVER_BLOCK,
                        ModBlocks.STEEL_BLOCK,
                        ModBlocks.TIN_BLOCK,
                        ModBlocks.URANIUM_BLOCK,
                        ModBlocks.ZINC_BLOCK,
                        ModBlocks.RAW_ALUMINUM_BLOCK,
                        ModBlocks.RAW_LEAD_BLOCK,
                        ModBlocks.RAW_NICKEL_BLOCK,
                        ModBlocks.RAW_OSMIUM_BLOCK,
                        ModBlocks.RAW_PLATINUM_BLOCK,
                        ModBlocks.RAW_SILVER_BLOCK,
                        ModBlocks.RAW_TIN_BLOCK,
                        ModBlocks.RAW_URANIUM_BLOCK,
                        ModBlocks.RAW_ZINC_BLOCK);

        this.tag(ModTags.Blocks.ORES)
                .add(
                        ModBlocks.ALUMINUM_ORE,
                        ModBlocks.DEEPSLATE_ALUMINUM_ORE,
                        ModBlocks.APATITE_ORE,
                        ModBlocks.DEEPSLATE_APATITE_ORE,
                        ModBlocks.CINNABAR_ORE,
                        ModBlocks.DEEPSLATE_CINNABAR_ORE,
                        ModBlocks.LEAD_ORE,
                        ModBlocks.DEEPSLATE_LEAD_ORE,
                        ModBlocks.NICKEL_ORE,
                        ModBlocks.DEEPSLATE_NICKEL_ORE,
                        ModBlocks.OSMIUM_ORE,
                        ModBlocks.DEEPSLATE_OSMIUM_ORE,
                        ModBlocks.PLATINUM_ORE,
                        ModBlocks.DEEPSLATE_PLATINUM_ORE,
                        ModBlocks.RUBY_ORE,
                        ModBlocks.DEEPSLATE_RUBY_ORE,
                        ModBlocks.SAPPHIRE_ORE,
                        ModBlocks.DEEPSLATE_SAPPHIRE_ORE,
                        ModBlocks.SILVER_ORE,
                        ModBlocks.DEEPSLATE_SILVER_ORE,
                        ModBlocks.TIN_ORE,
                        ModBlocks.DEEPSLATE_TIN_ORE,
                        ModBlocks.URANIUM_ORE,
                        ModBlocks.DEEPSLATE_URANIUM_ORE,
                        ModBlocks.ZINC_ORE,
                        ModBlocks.DEEPSLATE_ZINC_ORE);
    }
}
