package com.furtabs.asylumresources.datagen;

import com.furtabs.asylumresources.item.ModItems;
import com.furtabs.asylumresources.util.ModTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModItemTagGenerator extends ItemTagsProvider {
    public ModItemTagGenerator(PackOutput p_275343_, CompletableFuture<HolderLookup.Provider> p_275729_,
                               CompletableFuture<TagLookup<Block>> p_275322_, @Nullable ExistingFileHelper existingFileHelper) {
        super(p_275343_, p_275729_, p_275322_, com.furtabs.asylumresources.AsylumRes.MOD_ID, existingFileHelper);
    }


    @Override
    protected void addTags(HolderLookup.Provider pProvider) {
        this.tag(ModTags.Items.COINS)
                .add(
                        ModItems.ALUMINUM_COIN.get(),
                        ModItems.PLATINUM_COIN.get(),
                        ModItems.SILVER_COIN.get(),
                        ModItems.NICKEL_COIN.get(),
                        ModItems.URANIUM_COIN.get(),
                        ModItems.LEAD_COIN.get(),
                        ModItems.OSMIUM_COIN.get(),
                        ModItems.TIN_COIN.get(),
                        ModItems.ZINC_COIN.get(),
                        ModItems.IRON_COIN.get(),
                        ModItems.COPPER_COIN.get(),
                        ModItems.GOLD_COIN.get(),
                        ModItems.NETHERITE_COIN.get(),
                        ModItems.RUBY_COIN.get(),
                        ModItems.SAPPHIRE_COIN.get(),
                        ModItems.APATITE_COIN.get(),
                        ModItems.CINNABAR_COIN.get(),
                        ModItems.DIAMOND_COIN.get(),
                        ModItems.EMERALD_COIN.get(),
                        ModItems.LAPIS_LAZULI_COIN.get(),
                        ModItems.QUARTZ_COIN.get(),
                        ModItems.BRONZE_COIN.get(),
                        ModItems.CONSTANTAN_COIN.get(),
                        ModItems.INVAR_COIN.get(),
                        ModItems.SIGNALUM_COIN.get(),
                        ModItems.REFINED_OBSIDIAN_COIN.get(),
                        ModItems.REFINED_GLOWSTONE_COIN.get(),
                        ModItems.BRASS_COIN.get(),
                        ModItems.ELECTRUM_COIN.get(),
                        ModItems.ENDERIUM_COIN.get(),
                        ModItems.STEEL_COIN.get(),
                        ModItems.ANDESITE_ALLOY_COIN.get(),
                        ModItems.LUMIUM_COIN.get(),
                        ModItems.ROSE_GOLD_COIN.get(),
                        ModItems.QUARTZ_ENRICHED_IRON_COIN.get(),
                        ModItems.IRON_COMPRESSED_COIN.get());

        this.tag(ModTags.Items.DUSTS)
                .add(
                        ModItems.ANDESITE_ALLOY_DUST.get(),
                        ModItems.AMETHYST_DUST.get(),
                        ModItems.ALUMINUM_DUST.get(),
                        ModItems.APATITE_DUST.get(),
                        ModItems.BRASS_DUST.get(),
                        ModItems.BRONZE_DUST.get(),
                        ModItems.CALCITE_DUST.get(),
                        ModItems.CHARCOAL_DUST.get(),
                        ModItems.CINNABAR_DUST.get(),
                        ModItems.COAL_DUST.get(),
                        ModItems.CONSTANTAN_DUST.get(),
                        ModItems.COPPER_DUST.get(),
                        ModItems.DIAMOND_DUST.get(),
                        ModItems.ELECTRUM_DUST.get(),
                        ModItems.EMERALD_DUST.get(),
                        ModItems.ENDER_PEARL_DUST.get(),
                        ModItems.ENDERIUM_DUST.get(),
                        ModItems.GOLD_DUST.get(),
                        ModItems.GRAPHITE_DUST.get(),
                        ModItems.INVAR_DUST.get(),
                        ModItems.IRON_DUST.get(),
                        ModItems.LAPIS_LAZULI_DUST.get(),
                        ModItems.LEAD_DUST.get(),
                        ModItems.LUMIUM_DUST.get(),
                        ModItems.NETHERRACK_DUST.get(),
                        ModItems.NETHERITE_DUST.get(),
                        ModItems.NICKEL_DUST.get(),
                        ModItems.OBSIDIAN_DUST.get(),
                        ModItems.SIGNALUM_DUST.get(),
                        ModItems.OSMIUM_DUST.get(),
                        ModItems.PLATINUM_DUST.get(),
                        ModItems.PRISMARINE_DUST.get(),
                        ModItems.QUARTZ_DUST.get(),
                        ModItems.QUARTZ_ENRICHED_IRON_DUST.get(),
                        ModItems.REFINED_GLOWSTONE_DUST.get(),
                        ModItems.REFINED_OBSIDIAN_DUST.get(),
                        ModItems.ROSE_GOLD_DUST.get(),
                        ModItems.RUBY_DUST.get(),
                        ModItems.SAPPHIRE_DUST.get(),
                        ModItems.SILVER_DUST.get(),
                        ModItems.STEEL_DUST.get(),
                        ModItems.TIN_DUST.get(),
                        ModItems.URANIUM_DUST.get(),
                        ModItems.ZINC_DUST.get());

        this.tag(ModTags.Items.ENRICHED_DUSTS)
                .add(
                        ModItems.ENRICHED_URANIUM_DUST.get());

        this.tag(ModTags.Items.ENRICHED_MATERIALS)
                .add(
                        ModItems.ENRICHED_URANIUM.get());

        this.tag(ModTags.Items.POLISHED_GEMS)
                .add(
                        ModItems.POLISHED_RUBY.get(),
                        ModItems.POLISHED_SAPPHIRE.get(),
                        ModItems.POLISHED_APATITE.get(),
                        ModItems.POLISHED_CINNABAR.get(),
                        ModItems.POLISHED_DIAMOND.get(),
                        ModItems.POLISHED_EMERALD.get(),
                        ModItems.POLISHED_LAPIS_LAZULI.get(),
                        ModItems.POLISHED_QUARTZ.get());

        this.tag(ModTags.Items.RODS)
                .add(
                        ModItems.ANDESITE_ALLOY_ROD.get(),
                        ModItems.ALUMINUM_ROD.get(),
                        ModItems.BRASS_ROD.get(),
                        ModItems.BRONZE_ROD.get(),
                        ModItems.CINNABAR_ROD.get(),
                        ModItems.CONSTANTAN_ROD.get(),
                        ModItems.COPPER_ROD.get(),
                        ModItems.ELECTRUM_ROD.get(),
                        ModItems.ENDERIUM_ROD.get(),
                        ModItems.GOLD_ROD.get(),
                        ModItems.GRAPHITE_ROD.get(),
                        ModItems.INVAR_ROD.get(),
                        ModItems.IRON_ROD.get(),
                        ModItems.LEAD_ROD.get(),
                        ModItems.LUMIUM_ROD.get(),
                        ModItems.NETHERITE_ROD.get(),
                        ModItems.NICKEL_ROD.get(),
                        ModItems.SIGNALUM_ROD.get(),
                        ModItems.OSMIUM_ROD.get(),
                        ModItems.PLASTIC_ROD.get(),
                        ModItems.PLATINUM_ROD.get(),
                        ModItems.QUARTZ_ENRICHED_IRON_ROD.get(),
                        ModItems.REFINED_GLOWSTONE_ROD.get(),
                        ModItems.REFINED_OBSIDIAN_ROD.get(),
                        ModItems.ROSE_GOLD_ROD.get(),
                        ModItems.RUBY_ROD.get(),
                        ModItems.SAPPHIRE_ROD.get(),
                        ModItems.SILVER_ROD.get(),
                        ModItems.STEEL_ROD.get(),
                        ModItems.TIN_ROD.get(),
                        ModItems.URANIUM_ROD.get(),
                        ModItems.ZINC_ROD.get());

        this.tag(ModTags.Items.PLATES)
                .add(
                        ModItems.ANDESITE_ALLOY_PLATE.get(),
                        ModItems.APATITE_PLATE.get(),
                        ModItems.BRASS_PLATE.get(),
                        ModItems.BRONZE_PLATE.get(),
                        ModItems.CINNABAR_PLATE.get(),
                        ModItems.CONSTANTAN_PLATE.get(),
                        ModItems.COPPER_PLATE.get(),
                        ModItems.DIAMOND_PLATE.get(),
                        ModItems.ELECTRUM_PLATE.get(),
                        ModItems.EMERALD_PLATE.get(),
                        ModItems.ENDERIUM_PLATE.get(),
                        ModItems.GOLD_PLATE.get(),
                        ModItems.GRAPHITE_PLATE.get(),
                        ModItems.INVAR_PLATE.get(),
                        ModItems.IRON_PLATE.get(),
                        ModItems.LAPIS_LAZULI_PLATE.get(),
                        ModItems.LEAD_PLATE.get(),
                        ModItems.LUMIUM_PLATE.get(),
                        ModItems.NETHERITE_PLATE.get(),
                        ModItems.NICKEL_PLATE.get(),
                        ModItems.SIGNALUM_PLATE.get(),
                        ModItems.OSMIUM_PLATE.get(),
                        ModItems.PLASTIC_PLATE.get(),
                        ModItems.PLATINUM_PLATE.get(),
                        ModItems.QUARTZ_PLATE.get(),
                        ModItems.QUARTZ_ENRICHED_IRON_PLATE.get(),
                        ModItems.REFINED_GLOWSTONE_PLATE.get(),
                        ModItems.REFINED_OBSIDIAN_PLATE.get(),
                        ModItems.ROSE_GOLD_PLATE.get(),
                        ModItems.RUBY_PLATE.get(),
                        ModItems.SAPPHIRE_PLATE.get(),
                        ModItems.SILVER_PLATE.get(),
                        ModItems.STEEL_PLATE.get(),
                        ModItems.TIN_PLATE.get(),
                        ModItems.URANIUM_PLATE.get(),
                        ModItems.ZINC_PLATE.get());

        this.tag(ModTags.Items.GEARS)
                .add(
                        ModItems.ANDESITE_ALLOY_GEAR.get(),
                        ModItems.ALUMINUM_GEAR.get(),
                        ModItems.BRASS_GEAR.get(),
                        ModItems.BRONZE_GEAR.get(),
                        ModItems.CONSTANTAN_GEAR.get(),
                        ModItems.COPPER_GEAR.get(),
                        ModItems.DIAMOND_GEAR.get(),
                        ModItems.ELECTRUM_GEAR.get(),
                        ModItems.EMERALD_GEAR.get(),
                        ModItems.ENDERIUM_GEAR.get(),
                        ModItems.GOLD_GEAR.get(),
                        ModItems.INVAR_GEAR.get(),
                        ModItems.IRON_GEAR.get(),
                        ModItems.LAPIS_LAZULI_GEAR.get(),
                        ModItems.LEAD_GEAR.get(),
                        ModItems.LUMIUM_GEAR.get(),
                        ModItems.NETHERITE_GEAR.get(),
                        ModItems.NICKEL_GEAR.get(),
                        ModItems.SIGNALUM_GEAR.get(),
                        ModItems.OSMIUM_GEAR.get(),
                        ModItems.PLATINUM_GEAR.get(),
                        ModItems.QUARTZ_GEAR.get(),
                        ModItems.QUARTZ_ENRICHED_IRON_GEAR.get(),
                        ModItems.REFINED_OBSIDIAN_GEAR.get(),
                        ModItems.REFINED_GLOWSTONE_GEAR.get(),
                        ModItems.ROSE_GOLD_GEAR.get(),
                        ModItems.RUBY_GEAR.get(),
                        ModItems.SAPPHIRE_GEAR.get(),
                        ModItems.SILVER_GEAR.get(),
                        ModItems.STEEL_GEAR.get(),
                        ModItems.TIN_GEAR.get(),
                        ModItems.URANIUM_GEAR.get(),
                        ModItems.ZINC_GEAR.get());

        this.tag(ModTags.Items.GEMS)
                .add(
                        ModItems.APATITE.get(),
                        ModItems.CINNABAR.get(),
                        ModItems.RUBY.get(),
                        ModItems.SAPPHIRE.get());

        this.tag(ModTags.Items.NUGGETS)
                .add(
                        ModItems.ANDESITE_ALLOY_NUGGET.get(),
                        ModItems.ALUMINUM_NUGGET.get(),
                        ModItems.BRASS_NUGGET.get(),
                        ModItems.BRONZE_NUGGET.get(),
                        ModItems.CONSTANTAN_NUGGET.get(),
                        ModItems.ELECTRUM_NUGGET.get(),
                        ModItems.ENDERIUM_NUGGET.get(),
                        ModItems.INVAR_NUGGET.get(),
                        ModItems.LEAD_NUGGET.get(),
                        ModItems.LUMIUM_NUGGET.get(),
                        ModItems.NICKEL_NUGGET.get(),
                        ModItems.SIGNALUM_NUGGET.get(),
                        ModItems.OSMIUM_NUGGET.get(),
                        ModItems.PLATINUM_NUGGET.get(),
                        ModItems.QUARTZ_ENRICHED_IRON_NUGGET.get(),
                        ModItems.REFINED_GLOWSTONE_INGOT.get(),
                        ModItems.REFINED_OBSIDIAN_NUGGET.get(),
                        ModItems.ROSE_GOLD_NUGGET.get(),
                        ModItems.SILVER_NUGGET.get(),
                        ModItems.STEEL_NUGGET.get(),
                        ModItems.TIN_NUGGET.get(),
                        ModItems.URANIUM_NUGGET.get(),
                        ModItems.ZINC_NUGGET.get());

        this.tag(ModTags.Items.INGOTS)
                .add(
                        ModItems.ALUMINUM_INGOT.get(),
                        ModItems.ANDESITE_ALLOY_INGOT.get(),
                        ModItems.BRASS_INGOT.get(),
                        ModItems.BRONZE_INGOT.get(),
                        ModItems.CONSTANTAN_INGOT.get(),
                        ModItems.ELECTRUM_INGOT.get(),
                        ModItems.ENDERIUM_INGOT.get(),
                        ModItems.GRAPHITE_INGOT.get(),
                        ModItems.INVAR_INGOT.get(),
                        ModItems.IRON_COMPRESSED_INGOT.get(),
                        ModItems.LEAD_INGOT.get(),
                        ModItems.LUMIUM_INGOT.get(),
                        ModItems.NICKEL_INGOT.get(),
                        ModItems.OSMIUM_INGOT.get(),
                        ModItems.PLATINUM_INGOT.get(),
                        ModItems.REFINED_GLOWSTONE_INGOT.get(),
                        ModItems.REFINED_OBSIDIAN_INGOT.get(),
                        ModItems.ROSE_GOLD_INGOT.get(),
                        ModItems.SIGNALUM_INGOT.get(),
                        ModItems.SILVER_INGOT.get(),
                        ModItems.STEEL_INGOT.get(),
                        ModItems.TIN_INGOT.get(),
                        ModItems.ZINC_INGOT.get());

        this.tag(ModTags.Items.RAW_MATERIALS)
                .add(
                        ModItems.RAW_ALUMINUM.get(),
                        ModItems.RAW_LEAD.get(),
                        ModItems.RAW_NICKEL.get(),
                        ModItems.RAW_OSMIUM.get(),
                        ModItems.RAW_PLATINUM.get(),
                        ModItems.RAW_SILVER.get(),
                        ModItems.RAW_TIN.get(),
                        ModItems.RAW_URANIUM.get(),
                        ModItems.RAW_ZINC.get());

        // Create individual neoforge material tags
        createIndividualMaterialTags();

        // Create individual c: material tags that reference the neoforge tags
        createIndividualCMaterialTags();

        // Ensure neoforge:hammers exists (empty is fine) so cross-namespace mirror doesn't fail
        this.tag(ModTags.Items.HAMMERS);

        // Mirror NeoForge tags into common `c:` tags for cross-loader compatibility
        this.tag(com.furtabs.asylumresources.util.ModTags.CItems.HAMMERS)
                .addTag(ModTags.Items.HAMMERS);
        this.tag(com.furtabs.asylumresources.util.ModTags.CItems.COINS)
                .addTag(ModTags.Items.COINS);
        this.tag(com.furtabs.asylumresources.util.ModTags.CItems.DUSTS)
                .addTag(ModTags.Items.DUSTS);
        this.tag(com.furtabs.asylumresources.util.ModTags.CItems.ENRICHED_DUSTS)
                .addTag(ModTags.Items.ENRICHED_DUSTS);
        this.tag(com.furtabs.asylumresources.util.ModTags.CItems.ENRICHED_MATERIALS)
                .addTag(ModTags.Items.ENRICHED_MATERIALS);
        this.tag(com.furtabs.asylumresources.util.ModTags.CItems.POLISHED_GEMS)
                .addTag(ModTags.Items.POLISHED_GEMS);
        this.tag(com.furtabs.asylumresources.util.ModTags.CItems.RODS)
                .addTag(ModTags.Items.RODS);
        this.tag(com.furtabs.asylumresources.util.ModTags.CItems.PLATES)
                .addTag(ModTags.Items.PLATES);
        this.tag(com.furtabs.asylumresources.util.ModTags.CItems.GEARS)
                .addTag(ModTags.Items.GEARS);
        this.tag(com.furtabs.asylumresources.util.ModTags.CItems.GEMS)
                .addTag(ModTags.Items.GEMS);
        this.tag(com.furtabs.asylumresources.util.ModTags.CItems.NUGGETS)
                .addTag(ModTags.Items.NUGGETS);
        this.tag(com.furtabs.asylumresources.util.ModTags.CItems.INGOTS)
                .addTag(ModTags.Items.INGOTS);
        this.tag(com.furtabs.asylumresources.util.ModTags.CItems.RAW_MATERIALS)
                .addTag(ModTags.Items.RAW_MATERIALS);
    }

    private void createIndividualMaterialTags() {
        createIndividualIngotTags();
        createIndividualDustTags();
        createIndividualNuggetTags();
        createIndividualPlateTags();
        createIndividualGearTags();
        createIndividualRodTags();
        createIndividualCoinTags();
        createIndividualGemTags();
        createIndividualRawMaterialTags();
    }

    private void createIndividualIngotTags() {
        this.tag(forgeTag("ingots/aluminum"))
                .add(ModItems.ALUMINUM_INGOT.get());
        this.tag(forgeTag("ingots/andesite_alloy"))
                .add(ModItems.ANDESITE_ALLOY_INGOT.get());
        this.tag(forgeTag("ingots/brass"))
                .add(ModItems.BRASS_INGOT.get());
        this.tag(forgeTag("ingots/bronze"))
                .add(ModItems.BRONZE_INGOT.get());
        this.tag(forgeTag("ingots/constantan"))
                .add(ModItems.CONSTANTAN_INGOT.get());
        this.tag(forgeTag("ingots/electrum"))
                .add(ModItems.ELECTRUM_INGOT.get());
        this.tag(forgeTag("ingots/enderium"))
                .add(ModItems.ENDERIUM_INGOT.get());
        this.tag(forgeTag("ingots/graphite"))
                .add(ModItems.GRAPHITE_INGOT.get());
        this.tag(forgeTag("ingots/invar"))
                .add(ModItems.INVAR_INGOT.get());
        this.tag(forgeTag("ingots/iron_compressed"))
                .add(ModItems.IRON_COMPRESSED_INGOT.get());
        this.tag(forgeTag("ingots/lead"))
                .add(ModItems.LEAD_INGOT.get());
        this.tag(forgeTag("ingots/lumium"))
                .add(ModItems.LUMIUM_INGOT.get());
        this.tag(forgeTag("ingots/nickel"))
                .add(ModItems.NICKEL_INGOT.get());
        this.tag(forgeTag("ingots/osmium"))
                .add(ModItems.OSMIUM_INGOT.get());
        this.tag(forgeTag("ingots/platinum"))
                .add(ModItems.PLATINUM_INGOT.get());
        this.tag(forgeTag("ingots/quartz_enriched_iron"))
                .add(ModItems.QUARTZ_ENRICHED_IRON_INGOT.get());
        this.tag(forgeTag("ingots/refined_glowstone"))
                .add(ModItems.REFINED_GLOWSTONE_INGOT.get());
        this.tag(forgeTag("ingots/refined_obsidian"))
                .add(ModItems.REFINED_OBSIDIAN_INGOT.get());
        this.tag(forgeTag("ingots/rose_gold"))
                .add(ModItems.ROSE_GOLD_INGOT.get());
        this.tag(forgeTag("ingots/signalum"))
                .add(ModItems.SIGNALUM_INGOT.get());
        this.tag(forgeTag("ingots/silver"))
                .add(ModItems.SILVER_INGOT.get());
        this.tag(forgeTag("ingots/steel"))
                .add(ModItems.STEEL_INGOT.get());
        this.tag(forgeTag("ingots/tin"))
                .add(ModItems.TIN_INGOT.get());
        this.tag(forgeTag("ingots/uranium"))
                .add(ModItems.URANIUM_INGOT.get());
        this.tag(forgeTag("ingots/zinc"))
                .add(ModItems.ZINC_INGOT.get());
    }

    private void createIndividualDustTags() {
        this.tag(forgeTag("dusts/aluminum"))
                .add(ModItems.ALUMINUM_DUST.get());
        this.tag(forgeTag("dusts/andesite_alloy"))
                .add(ModItems.ANDESITE_ALLOY_DUST.get());
        this.tag(forgeTag("dusts/brass"))
                .add(ModItems.BRASS_DUST.get());
        this.tag(forgeTag("dusts/bronze"))
                .add(ModItems.BRONZE_DUST.get());
        this.tag(forgeTag("dusts/constantan"))
                .add(ModItems.CONSTANTAN_DUST.get());
        this.tag(forgeTag("dusts/electrum"))
                .add(ModItems.ELECTRUM_DUST.get());
        this.tag(forgeTag("dusts/enderium"))
                .add(ModItems.ENDERIUM_DUST.get());
        this.tag(forgeTag("dusts/graphite"))
                .add(ModItems.GRAPHITE_DUST.get());
        this.tag(forgeTag("dusts/invar"))
                .add(ModItems.INVAR_DUST.get());
        this.tag(forgeTag("dusts/iron"))
                .add(ModItems.IRON_DUST.get());
        this.tag(forgeTag("dusts/lead"))
                .add(ModItems.LEAD_DUST.get());
        this.tag(forgeTag("dusts/lumium"))
                .add(ModItems.LUMIUM_DUST.get());
        this.tag(forgeTag("dusts/nickel"))
                .add(ModItems.NICKEL_DUST.get());
        this.tag(forgeTag("dusts/osmium"))
                .add(ModItems.OSMIUM_DUST.get());
        this.tag(forgeTag("dusts/platinum"))
                .add(ModItems.PLATINUM_DUST.get());
        this.tag(forgeTag("dusts/refined_glowstone"))
                .add(ModItems.REFINED_GLOWSTONE_DUST.get());
        this.tag(forgeTag("dusts/refined_obsidian"))
                .add(ModItems.REFINED_OBSIDIAN_DUST.get());
        this.tag(forgeTag("dusts/rose_gold"))
                .add(ModItems.ROSE_GOLD_DUST.get());
        this.tag(forgeTag("dusts/signalum"))
                .add(ModItems.SIGNALUM_DUST.get());
        this.tag(forgeTag("dusts/silver"))
                .add(ModItems.SILVER_DUST.get());
        this.tag(forgeTag("dusts/steel"))
                .add(ModItems.STEEL_DUST.get());
        this.tag(forgeTag("dusts/tin"))
                .add(ModItems.TIN_DUST.get());
        this.tag(forgeTag("dusts/zinc"))
                .add(ModItems.ZINC_DUST.get());
    }

    private void createIndividualNuggetTags() {
        this.tag(forgeTag("nuggets/aluminum"))
                .add(ModItems.ALUMINUM_NUGGET.get());
        this.tag(forgeTag("nuggets/andesite_alloy"))
                .add(ModItems.ANDESITE_ALLOY_NUGGET.get());
        this.tag(forgeTag("nuggets/brass"))
                .add(ModItems.BRASS_NUGGET.get());
        this.tag(forgeTag("nuggets/bronze"))
                .add(ModItems.BRONZE_NUGGET.get());
        this.tag(forgeTag("nuggets/constantan"))
                .add(ModItems.CONSTANTAN_NUGGET.get());
        this.tag(forgeTag("nuggets/electrum"))
                .add(ModItems.ELECTRUM_NUGGET.get());
        this.tag(forgeTag("nuggets/enderium"))
                .add(ModItems.ENDERIUM_NUGGET.get());
        this.tag(forgeTag("nuggets/invar"))
                .add(ModItems.INVAR_NUGGET.get());
        this.tag(forgeTag("nuggets/lead"))
                .add(ModItems.LEAD_NUGGET.get());
        this.tag(forgeTag("nuggets/lumium"))
                .add(ModItems.LUMIUM_NUGGET.get());
        this.tag(forgeTag("nuggets/nickel"))
                .add(ModItems.NICKEL_NUGGET.get());
        this.tag(forgeTag("nuggets/signalum"))
                .add(ModItems.SIGNALUM_NUGGET.get());
        this.tag(forgeTag("nuggets/osmium"))
                .add(ModItems.OSMIUM_NUGGET.get());
        this.tag(forgeTag("nuggets/platinum"))
                .add(ModItems.PLATINUM_NUGGET.get());
        this.tag(forgeTag("nuggets/refined_glowstone"))
                .add(ModItems.REFINED_GLOWSTONE_NUGGET.get());
        this.tag(forgeTag("nuggets/refined_obsidian"))
                .add(ModItems.REFINED_OBSIDIAN_NUGGET.get());
        this.tag(forgeTag("nuggets/rose_gold"))
                .add(ModItems.ROSE_GOLD_NUGGET.get());
        this.tag(forgeTag("nuggets/silver"))
                .add(ModItems.SILVER_NUGGET.get());
        this.tag(forgeTag("nuggets/steel"))
                .add(ModItems.STEEL_NUGGET.get());
        this.tag(forgeTag("nuggets/tin"))
                .add(ModItems.TIN_NUGGET.get());
        this.tag(forgeTag("nuggets/zinc"))
                .add(ModItems.ZINC_NUGGET.get());
    }

    private void createIndividualPlateTags() {
        this.tag(forgeTag("plates/aluminum"))
                .add(ModItems.ALUMINUM_PLATE.get());
        this.tag(forgeTag("plates/andesite_alloy"))
                .add(ModItems.ANDESITE_ALLOY_PLATE.get());
        this.tag(forgeTag("plates/apatite"))
                .add(ModItems.APATITE_PLATE.get());
        this.tag(forgeTag("plates/brass"))
                .add(ModItems.BRASS_PLATE.get());
        this.tag(forgeTag("plates/bronze"))
                .add(ModItems.BRONZE_PLATE.get());
        this.tag(forgeTag("plates/constantan"))
                .add(ModItems.CONSTANTAN_PLATE.get());
        this.tag(forgeTag("plates/electrum"))
                .add(ModItems.ELECTRUM_PLATE.get());
        this.tag(forgeTag("plates/enderium"))
                .add(ModItems.ENDERIUM_PLATE.get());
        this.tag(forgeTag("plates/graphite"))
                .add(ModItems.GRAPHITE_PLATE.get());
        this.tag(forgeTag("plates/invar"))
                .add(ModItems.INVAR_PLATE.get());
        this.tag(forgeTag("plates/iron"))
                .add(ModItems.IRON_PLATE.get());
        this.tag(forgeTag("plates/lead"))
                .add(ModItems.LEAD_PLATE.get());
        this.tag(forgeTag("plates/lumium"))
                .add(ModItems.LUMIUM_PLATE.get());
        this.tag(forgeTag("plates/nickel"))
                .add(ModItems.NICKEL_PLATE.get());
        this.tag(forgeTag("plates/signalum"))
                .add(ModItems.SIGNALUM_PLATE.get());
        this.tag(forgeTag("plates/osmium"))
                .add(ModItems.OSMIUM_PLATE.get());
        this.tag(forgeTag("plates/platinum"))
                .add(ModItems.PLATINUM_PLATE.get());
        this.tag(forgeTag("plates/refined_glowstone"))
                .add(ModItems.REFINED_GLOWSTONE_PLATE.get());
        this.tag(forgeTag("plates/refined_obsidian"))
                .add(ModItems.REFINED_OBSIDIAN_PLATE.get());
        this.tag(forgeTag("plates/rose_gold"))
                .add(ModItems.ROSE_GOLD_PLATE.get());
        this.tag(forgeTag("plates/silver"))
                .add(ModItems.SILVER_PLATE.get());
        this.tag(forgeTag("plates/steel"))
                .add(ModItems.STEEL_PLATE.get());
        this.tag(forgeTag("plates/tin"))
                .add(ModItems.TIN_PLATE.get());
        this.tag(forgeTag("plates/zinc"))
                .add(ModItems.ZINC_PLATE.get());
    }

    private void createIndividualGearTags() {
        this.tag(forgeTag("gears/aluminum"))
                .add(ModItems.ALUMINUM_GEAR.get());
        this.tag(forgeTag("gears/andesite_alloy"))
                .add(ModItems.ANDESITE_ALLOY_GEAR.get());
        this.tag(forgeTag("gears/brass"))
                .add(ModItems.BRASS_GEAR.get());
        this.tag(forgeTag("gears/bronze"))
                .add(ModItems.BRONZE_GEAR.get());
        this.tag(forgeTag("gears/constantan"))
                .add(ModItems.CONSTANTAN_GEAR.get());
        this.tag(forgeTag("gears/electrum"))
                .add(ModItems.ELECTRUM_GEAR.get());
        this.tag(forgeTag("gears/enderium"))
                .add(ModItems.ENDERIUM_GEAR.get());
        this.tag(forgeTag("gears/invar"))
                .add(ModItems.INVAR_GEAR.get());
        this.tag(forgeTag("gears/iron"))
                .add(ModItems.IRON_GEAR.get());
        this.tag(forgeTag("gears/lead"))
                .add(ModItems.LEAD_GEAR.get());
        this.tag(forgeTag("gears/lumium"))
                .add(ModItems.LUMIUM_GEAR.get());
        this.tag(forgeTag("gears/nickel"))
                .add(ModItems.NICKEL_GEAR.get());
        this.tag(forgeTag("gears/signalum"))
                .add(ModItems.SIGNALUM_GEAR.get());
        this.tag(forgeTag("gears/osmium"))
                .add(ModItems.OSMIUM_GEAR.get());
        this.tag(forgeTag("gears/platinum"))
                .add(ModItems.PLATINUM_GEAR.get());
        this.tag(forgeTag("gears/refined_glowstone"))
                .add(ModItems.REFINED_GLOWSTONE_GEAR.get());
        this.tag(forgeTag("gears/refined_obsidian"))
                .add(ModItems.REFINED_OBSIDIAN_GEAR.get());
        this.tag(forgeTag("gears/rose_gold"))
                .add(ModItems.ROSE_GOLD_GEAR.get());
        this.tag(forgeTag("gears/silver"))
                .add(ModItems.SILVER_GEAR.get());
        this.tag(forgeTag("gears/steel"))
                .add(ModItems.STEEL_GEAR.get());
        this.tag(forgeTag("gears/tin"))
                .add(ModItems.TIN_GEAR.get());
        this.tag(forgeTag("gears/zinc"))
                .add(ModItems.ZINC_GEAR.get());
    }

    private void createIndividualRodTags() {
        // Create neoforge:rods/aluminum tag
        this.tag(forgeTag("rods/aluminum"))
                .add(ModItems.ALUMINUM_ROD.get());
        this.tag(forgeTag("rods/andesite_alloy"))
                .add(ModItems.ANDESITE_ALLOY_ROD.get());
        this.tag(forgeTag("rods/brass"))
                .add(ModItems.BRASS_ROD.get());
        this.tag(forgeTag("rods/bronze"))
                .add(ModItems.BRONZE_ROD.get());
        this.tag(forgeTag("rods/constantan"))
                .add(ModItems.CONSTANTAN_ROD.get());
        this.tag(forgeTag("rods/electrum"))
                .add(ModItems.ELECTRUM_ROD.get());
        this.tag(forgeTag("rods/enderium"))
                .add(ModItems.ENDERIUM_ROD.get());
        this.tag(forgeTag("rods/graphite"))
                .add(ModItems.GRAPHITE_ROD.get());
        this.tag(forgeTag("rods/invar"))
                .add(ModItems.INVAR_ROD.get());
        this.tag(forgeTag("rods/iron"))
                .add(ModItems.IRON_ROD.get());
        this.tag(forgeTag("rods/lead"))
                .add(ModItems.LEAD_ROD.get());
        this.tag(forgeTag("rods/lumium"))
                .add(ModItems.LUMIUM_ROD.get());
        this.tag(forgeTag("rods/nickel"))
                .add(ModItems.NICKEL_ROD.get());
        this.tag(forgeTag("rods/signalum"))
                .add(ModItems.SIGNALUM_ROD.get());
        this.tag(forgeTag("rods/osmium"))
                .add(ModItems.OSMIUM_ROD.get());
        this.tag(forgeTag("rods/platinum"))
                .add(ModItems.PLATINUM_ROD.get());
        this.tag(forgeTag("rods/refined_glowstone"))
                .add(ModItems.REFINED_GLOWSTONE_ROD.get());
        this.tag(forgeTag("rods/refined_obsidian"))
                .add(ModItems.REFINED_OBSIDIAN_ROD.get());
        this.tag(forgeTag("rods/rose_gold"))
                .add(ModItems.ROSE_GOLD_ROD.get());
        this.tag(forgeTag("rods/silver"))
                .add(ModItems.SILVER_ROD.get());
        this.tag(forgeTag("rods/steel"))
                .add(ModItems.STEEL_ROD.get());
        this.tag(forgeTag("rods/tin"))
                .add(ModItems.TIN_ROD.get());
        this.tag(forgeTag("rods/zinc"))
                .add(ModItems.ZINC_ROD.get());
    }

    private void createIndividualCoinTags() {
        // Create neoforge:coins/aluminum tag
        this.tag(forgeTag("coins/aluminum"))
                .add(ModItems.ALUMINUM_COIN.get());
        this.tag(forgeTag("coins/andesite_alloy"))
                .add(ModItems.ANDESITE_ALLOY_COIN.get());
        this.tag(forgeTag("coins/brass"))
                .add(ModItems.BRASS_COIN.get());
        this.tag(forgeTag("coins/bronze"))
                .add(ModItems.BRONZE_COIN.get());
        this.tag(forgeTag("coins/constantan"))
                .add(ModItems.CONSTANTAN_COIN.get());
        this.tag(forgeTag("coins/electrum"))
                .add(ModItems.ELECTRUM_COIN.get());
        this.tag(forgeTag("coins/enderium"))
                .add(ModItems.ENDERIUM_COIN.get());
        this.tag(forgeTag("coins/invar"))
                .add(ModItems.INVAR_COIN.get());
        this.tag(forgeTag("coins/iron_compressed"))
                .add(ModItems.IRON_COMPRESSED_COIN.get());
        this.tag(forgeTag("coins/lead"))
                .add(ModItems.LEAD_COIN.get());
        this.tag(forgeTag("coins/lumium"))
                .add(ModItems.LUMIUM_COIN.get());
        this.tag(forgeTag("coins/nickel"))
                .add(ModItems.NICKEL_COIN.get());
        this.tag(forgeTag("coins/signalum"))
                .add(ModItems.SIGNALUM_COIN.get());
        this.tag(forgeTag("coins/osmium"))
                .add(ModItems.OSMIUM_COIN.get());
        this.tag(forgeTag("coins/platinum"))
                .add(ModItems.PLATINUM_COIN.get());
        this.tag(forgeTag("coins/refined_glowstone"))
                .add(ModItems.REFINED_GLOWSTONE_COIN.get());
        this.tag(forgeTag("coins/refined_obsidian"))
                .add(ModItems.REFINED_OBSIDIAN_COIN.get());
        this.tag(forgeTag("coins/rose_gold"))
                .add(ModItems.ROSE_GOLD_COIN.get());
        this.tag(forgeTag("coins/silver"))
                .add(ModItems.SILVER_COIN.get());
        this.tag(forgeTag("coins/steel"))
                .add(ModItems.STEEL_COIN.get());
        this.tag(forgeTag("coins/tin"))
                .add(ModItems.TIN_COIN.get());
        this.tag(forgeTag("coins/zinc"))
                .add(ModItems.ZINC_COIN.get());
    }

    private void createIndividualGemTags() {
        // Create neoforge:gems/apatite tag
        this.tag(forgeTag("gems/apatite"))
                .add(ModItems.APATITE.get());
        this.tag(forgeTag("gems/cinnabar"))
                .add(ModItems.CINNABAR.get());
        this.tag(forgeTag("gems/ruby"))
                .add(ModItems.RUBY.get());
        this.tag(forgeTag("gems/sapphire"))
                .add(ModItems.SAPPHIRE.get());
    }

    private void createIndividualRawMaterialTags() {
        // Create neoforge:raw_materials/aluminum tag
        this.tag(forgeTag("raw_materials/aluminum"))
                .add(ModItems.RAW_ALUMINUM.get());
        this.tag(forgeTag("raw_materials/lead"))
                .add(ModItems.RAW_LEAD.get());
        this.tag(forgeTag("raw_materials/nickel"))
                .add(ModItems.RAW_NICKEL.get());
        this.tag(forgeTag("raw_materials/osmium"))
                .add(ModItems.RAW_OSMIUM.get());
        this.tag(forgeTag("raw_materials/platinum"))
                .add(ModItems.RAW_PLATINUM.get());
        this.tag(forgeTag("raw_materials/silver"))
                .add(ModItems.RAW_SILVER.get());
        this.tag(forgeTag("raw_materials/tin"))
                .add(ModItems.RAW_TIN.get());
        this.tag(forgeTag("raw_materials/uranium"))
                .add(ModItems.RAW_URANIUM.get());
        this.tag(forgeTag("raw_materials/zinc"))
                .add(ModItems.RAW_ZINC.get());
    }

    private void createIndividualCMaterialTags() {
        // Create c:ingots/aluminum tag
        this.tag(commonTag("ingots/aluminum"))
                .add(ModItems.ALUMINUM_INGOT.get());
        this.tag(commonTag("ingots/andesite_alloy"))
                .add(ModItems.ANDESITE_ALLOY_INGOT.get());
        this.tag(commonTag("ingots/brass"))
                .add(ModItems.BRASS_INGOT.get());
        this.tag(commonTag("ingots/bronze"))
                .add(ModItems.BRONZE_INGOT.get());
        this.tag(commonTag("ingots/constantan"))
                .add(ModItems.CONSTANTAN_INGOT.get());
        this.tag(commonTag("ingots/electrum"))
                .add(ModItems.ELECTRUM_INGOT.get());
        this.tag(commonTag("ingots/enderium"))
                .add(ModItems.ENDERIUM_INGOT.get());
        this.tag(commonTag("ingots/graphite"))
                .add(ModItems.GRAPHITE_INGOT.get());
        this.tag(commonTag("ingots/invar"))
                .add(ModItems.INVAR_INGOT.get());
        this.tag(commonTag("ingots/iron_compressed"))
                .add(ModItems.IRON_COMPRESSED_INGOT.get());
        this.tag(commonTag("ingots/lead"))
                .add(ModItems.LEAD_INGOT.get());
        this.tag(commonTag("ingots/lumium"))
                .add(ModItems.LUMIUM_INGOT.get());
        this.tag(commonTag("ingots/nickel"))
                .add(ModItems.NICKEL_INGOT.get());
        this.tag(commonTag("ingots/osmium"))
                .add(ModItems.OSMIUM_INGOT.get());
        this.tag(commonTag("ingots/platinum"))
                .add(ModItems.PLATINUM_INGOT.get());
        this.tag(commonTag("ingots/refined_glowstone"))
                .add(ModItems.REFINED_GLOWSTONE_INGOT.get());
        this.tag(commonTag("ingots/refined_obsidian"))
                .add(ModItems.REFINED_OBSIDIAN_INGOT.get());
        this.tag(commonTag("ingots/rose_gold"))
                .add(ModItems.ROSE_GOLD_INGOT.get());
        this.tag(commonTag("ingots/signalum"))
                .add(ModItems.SIGNALUM_INGOT.get());
        this.tag(commonTag("ingots/silver"))
                .add(ModItems.SILVER_INGOT.get());
        this.tag(commonTag("ingots/steel"))
                .add(ModItems.STEEL_INGOT.get());
        this.tag(commonTag("ingots/tin"))
                .add(ModItems.TIN_INGOT.get());
        this.tag(commonTag("ingots/zinc"))
                .add(ModItems.ZINC_INGOT.get());

        // Create c:dusts/aluminum tag
        this.tag(commonTag("dusts/aluminum"))
                .add(ModItems.ALUMINUM_DUST.get());
        this.tag(commonTag("dusts/andesite_alloy"))
                .add(ModItems.ANDESITE_ALLOY_DUST.get());
        this.tag(commonTag("dusts/brass"))
                .add(ModItems.BRASS_DUST.get());
        this.tag(commonTag("dusts/bronze"))
                .add(ModItems.BRONZE_DUST.get());
        this.tag(commonTag("dusts/constantan"))
                .add(ModItems.CONSTANTAN_DUST.get());
        this.tag(commonTag("dusts/electrum"))
                .add(ModItems.ELECTRUM_DUST.get());
        this.tag(commonTag("dusts/enderium"))
                .add(ModItems.ENDERIUM_DUST.get());
        this.tag(commonTag("dusts/graphite"))
                .add(ModItems.GRAPHITE_DUST.get());
        this.tag(commonTag("dusts/invar"))
                .add(ModItems.INVAR_DUST.get());
        this.tag(commonTag("dusts/iron"))
                .add(ModItems.IRON_DUST.get());
        this.tag(commonTag("dusts/lead"))
                .add(ModItems.LEAD_DUST.get());
        this.tag(commonTag("dusts/lumium"))
                .add(ModItems.LUMIUM_DUST.get());
        this.tag(commonTag("dusts/nickel"))
                .add(ModItems.NICKEL_DUST.get());
        this.tag(commonTag("dusts/osmium"))
                .add(ModItems.OSMIUM_DUST.get());
        this.tag(commonTag("dusts/platinum"))
                .add(ModItems.PLATINUM_DUST.get());
        this.tag(commonTag("dusts/refined_glowstone"))
                .add(ModItems.REFINED_GLOWSTONE_DUST.get());
        this.tag(commonTag("dusts/refined_obsidian"))
                .add(ModItems.REFINED_OBSIDIAN_DUST.get());
        this.tag(commonTag("dusts/rose_gold"))
                .add(ModItems.ROSE_GOLD_DUST.get());
        this.tag(commonTag("dusts/signalum"))
                .add(ModItems.SIGNALUM_DUST.get());
        this.tag(commonTag("dusts/silver"))
                .add(ModItems.SILVER_DUST.get());
        this.tag(commonTag("dusts/steel"))
                .add(ModItems.STEEL_DUST.get());
        this.tag(commonTag("dusts/tin"))
                .add(ModItems.TIN_DUST.get());
        this.tag(commonTag("dusts/zinc"))
                .add(ModItems.ZINC_DUST.get());

        // Create c:nuggets/aluminum tag
        this.tag(commonTag("nuggets/aluminum"))
                .add(ModItems.ALUMINUM_NUGGET.get());
        this.tag(commonTag("nuggets/andesite_alloy"))
                .add(ModItems.ANDESITE_ALLOY_NUGGET.get());
        this.tag(commonTag("nuggets/brass"))
                .add(ModItems.BRASS_NUGGET.get());
        this.tag(commonTag("nuggets/bronze"))
                .add(ModItems.BRONZE_NUGGET.get());
        this.tag(commonTag("nuggets/constantan"))
                .add(ModItems.CONSTANTAN_NUGGET.get());
        this.tag(commonTag("nuggets/electrum"))
                .add(ModItems.ELECTRUM_NUGGET.get());
        this.tag(commonTag("nuggets/enderium"))
                .add(ModItems.ENDERIUM_NUGGET.get());
        this.tag(commonTag("nuggets/invar"))
                .add(ModItems.INVAR_NUGGET.get());
        this.tag(commonTag("nuggets/lead"))
                .add(ModItems.LEAD_NUGGET.get());
        this.tag(commonTag("nuggets/lumium"))
                .add(ModItems.LUMIUM_NUGGET.get());
        this.tag(commonTag("nuggets/nickel"))
                .add(ModItems.NICKEL_NUGGET.get());
        this.tag(commonTag("nuggets/signalum"))
                .add(ModItems.SIGNALUM_NUGGET.get());
        this.tag(commonTag("nuggets/osmium"))
                .add(ModItems.OSMIUM_NUGGET.get());
        this.tag(commonTag("nuggets/platinum"))
                .add(ModItems.PLATINUM_NUGGET.get());
        this.tag(commonTag("nuggets/refined_glowstone"))
                .add(ModItems.REFINED_GLOWSTONE_INGOT.get());
        this.tag(commonTag("nuggets/refined_obsidian"))
                .add(ModItems.REFINED_OBSIDIAN_NUGGET.get());
        this.tag(commonTag("nuggets/rose_gold"))
                .add(ModItems.ROSE_GOLD_NUGGET.get());
        this.tag(commonTag("nuggets/silver"))
                .add(ModItems.SILVER_NUGGET.get());
        this.tag(commonTag("nuggets/steel"))
                .add(ModItems.STEEL_NUGGET.get());
        this.tag(commonTag("nuggets/tin"))
                .add(ModItems.TIN_NUGGET.get());
        this.tag(commonTag("nuggets/zinc"))
                .add(ModItems.ZINC_NUGGET.get());

        // Create c:plates/aluminum tag
        this.tag(commonTag("plates/aluminum"))
                .add(ModItems.ALUMINUM_PLATE.get());
        this.tag(commonTag("plates/andesite_alloy"))
                .add(ModItems.ANDESITE_ALLOY_PLATE.get());
        this.tag(commonTag("plates/apatite"))
                .add(ModItems.APATITE_PLATE.get());
        this.tag(commonTag("plates/brass"))
                .add(ModItems.BRASS_PLATE.get());
        this.tag(commonTag("plates/bronze"))
                .add(ModItems.BRONZE_PLATE.get());
        this.tag(commonTag("plates/constantan"))
                .add(ModItems.CONSTANTAN_PLATE.get());
        this.tag(commonTag("plates/electrum"))
                .add(ModItems.ELECTRUM_PLATE.get());
        this.tag(commonTag("plates/enderium"))
                .add(ModItems.ENDERIUM_PLATE.get());
        this.tag(commonTag("plates/graphite"))
                .add(ModItems.GRAPHITE_PLATE.get());
        this.tag(commonTag("plates/invar"))
                .add(ModItems.INVAR_PLATE.get());
        this.tag(commonTag("plates/iron"))
                .add(ModItems.IRON_PLATE.get());
        this.tag(commonTag("plates/lead"))
                .add(ModItems.LEAD_PLATE.get());
        this.tag(commonTag("plates/lumium"))
                .add(ModItems.LUMIUM_PLATE.get());
        this.tag(commonTag("plates/nickel"))
                .add(ModItems.NICKEL_PLATE.get());
        this.tag(commonTag("plates/signalum"))
                .add(ModItems.SIGNALUM_PLATE.get());
        this.tag(commonTag("plates/osmium"))
                .add(ModItems.OSMIUM_PLATE.get());
        this.tag(commonTag("plates/platinum"))
                .add(ModItems.PLATINUM_PLATE.get());
        this.tag(commonTag("plates/refined_glowstone"))
                .add(ModItems.REFINED_GLOWSTONE_PLATE.get());
        this.tag(commonTag("plates/refined_obsidian"))
                .add(ModItems.REFINED_OBSIDIAN_PLATE.get());
        this.tag(commonTag("plates/rose_gold"))
                .add(ModItems.ROSE_GOLD_PLATE.get());
        this.tag(commonTag("plates/silver"))
                .add(ModItems.SILVER_PLATE.get());
        this.tag(commonTag("plates/steel"))
                .add(ModItems.STEEL_PLATE.get());
        this.tag(commonTag("plates/tin"))
                .add(ModItems.TIN_PLATE.get());
        this.tag(commonTag("plates/zinc"))
                .add(ModItems.ZINC_PLATE.get());

        // Create c:gears/aluminum tag
        this.tag(commonTag("gears/aluminum"))
                .add(ModItems.ALUMINUM_GEAR.get());
        this.tag(commonTag("gears/andesite_alloy"))
                .add(ModItems.ANDESITE_ALLOY_GEAR.get());
        this.tag(commonTag("gears/brass"))
                .add(ModItems.BRASS_GEAR.get());
        this.tag(commonTag("gears/bronze"))
                .add(ModItems.BRONZE_GEAR.get());
        this.tag(commonTag("gears/constantan"))
                .add(ModItems.CONSTANTAN_GEAR.get());
        this.tag(commonTag("gears/electrum"))
                .add(ModItems.ELECTRUM_GEAR.get());
        this.tag(commonTag("gears/enderium"))
                .add(ModItems.ENDERIUM_GEAR.get());

        this.tag(commonTag("gears/invar"))
                .add(ModItems.INVAR_GEAR.get());
        this.tag(commonTag("gears/iron"))
                .add(ModItems.IRON_GEAR.get());
        this.tag(commonTag("gears/lead"))
                .add(ModItems.LEAD_GEAR.get());
        this.tag(commonTag("gears/lumium"))
                .add(ModItems.LUMIUM_GEAR.get());
        this.tag(commonTag("gears/nickel"))
                .add(ModItems.NICKEL_GEAR.get());
        this.tag(commonTag("gears/signalum"))
                .add(ModItems.SIGNALUM_GEAR.get());
        this.tag(commonTag("gears/osmium"))
                .add(ModItems.OSMIUM_GEAR.get());
        this.tag(commonTag("gears/platinum"))
                .add(ModItems.PLATINUM_GEAR.get());
        this.tag(commonTag("gears/refined_glowstone"))
                .add(ModItems.REFINED_GLOWSTONE_GEAR.get());
        this.tag(commonTag("gears/refined_obsidian"))
                .add(ModItems.REFINED_OBSIDIAN_GEAR.get());
        this.tag(commonTag("gears/rose_gold"))
                .add(ModItems.ROSE_GOLD_GEAR.get());
        this.tag(commonTag("gears/silver"))
                .add(ModItems.SILVER_GEAR.get());
        this.tag(commonTag("gears/steel"))
                .add(ModItems.STEEL_GEAR.get());
        this.tag(commonTag("gears/tin"))
                .add(ModItems.TIN_GEAR.get());
        this.tag(commonTag("gears/zinc"))
                .add(ModItems.ZINC_GEAR.get());

        // Create c:gems/apatite tag
        this.tag(commonTag("gems/apatite"))
                .add(ModItems.APATITE.get());
        this.tag(commonTag("gems/cinnabar"))
                .add(ModItems.CINNABAR.get());
        this.tag(commonTag("gems/ruby"))
                .add(ModItems.RUBY.get());
        this.tag(commonTag("gems/sapphire"))
                .add(ModItems.SAPPHIRE.get());

        // Create c:raw_materials/aluminum tag
        this.tag(commonTag("raw_materials/aluminum"))
                .add(ModItems.RAW_ALUMINUM.get());
        this.tag(commonTag("raw_materials/lead"))
                .add(ModItems.RAW_LEAD.get());
        this.tag(commonTag("raw_materials/nickel"))
                .add(ModItems.RAW_NICKEL.get());
        this.tag(commonTag("raw_materials/osmium"))
                .add(ModItems.RAW_OSMIUM.get());
        this.tag(commonTag("raw_materials/platinum"))
                .add(ModItems.RAW_PLATINUM.get());
        this.tag(commonTag("raw_materials/silver"))
                .add(ModItems.RAW_SILVER.get());
        this.tag(commonTag("raw_materials/tin"))
                .add(ModItems.RAW_TIN.get());
        this.tag(commonTag("raw_materials/uranium"))
                .add(ModItems.RAW_URANIUM.get());
        this.tag(commonTag("raw_materials/zinc"))
                .add(ModItems.RAW_ZINC.get());
    }

    // Helper methods to create TagKey objects
    private TagKey<Item> forgeTag(String name) {
        return net.minecraft.tags.ItemTags.create(ResourceLocation.fromNamespaceAndPath("neoforge", name));
    }

    private TagKey<Item> commonTag(String name) {
        return net.minecraft.tags.ItemTags.create(ResourceLocation.fromNamespaceAndPath("c", name));
    }
}
