package com.endangerednayla.asylumresources.datagen;

import com.endangerednayla.asylumresources.block.ModBlocks;
import com.endangerednayla.asylumresources.util.ModTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.common.Tags;
import net.minecraftforge.common.data.BlockTagsProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagGenerator extends BlockTagsProvider {
    public ModBlockTagGenerator(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper ){
        super(output, lookupProvider, com.endangerednayla.asylumresources.AsylumRes.MOD_ID, existingFileHelper);
    }

    private static TagKey<Block> create(String p_203847_) {
        return TagKey.create(Registries.BLOCK, new ResourceLocation(p_203847_));
    }

    public static final TagKey<Block> MINEABLE_WITH_HAMMER = create("mineable/hammer");

    @Override
    protected void addTags(HolderLookup.Provider pProvider ){
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(
                        ModBlocks.Aluminum_Block.get(),
                        ModBlocks.Aluminum_Ore.get(),
                        ModBlocks.Andesite_Alloy_Block.get(),
                        ModBlocks.Apatite_Block.get(),
                        ModBlocks.Apatite_Ore.get(),
                        ModBlocks.Brass_Block.get(),
                        ModBlocks.Bronze_Block.get(),
                        ModBlocks.Cinnabar_Block.get(),
                        ModBlocks.Cinnabar_Ore.get(),
                        ModBlocks.Constantan_Block.get(),
                        ModBlocks.Deepslate_Aluminum_Ore.get(),
                        ModBlocks.Deepslate_Apatite_Ore.get(),
                        ModBlocks.Deepslate_Cinnabar_Ore.get(),
                        ModBlocks.Deepslate_Lead_Ore.get(),
                        ModBlocks.Deepslate_Nickel_Ore.get(),
                        ModBlocks.Deepslate_Osmium_Ore.get(),
                        ModBlocks.Deepslate_Platinum_Ore.get(),
                        ModBlocks.Deepslate_Ruby_Ore.get(),
                        ModBlocks.Deepslate_Sapphire_Ore.get(),
                        ModBlocks.Deepslate_Silver_Ore.get(),
                        ModBlocks.Deepslate_Tin_Ore.get(),
                        ModBlocks.Deepslate_Uranium_Ore.get(),
                        ModBlocks.Deepslate_Zinc_Ore.get(),
                        ModBlocks.Electrum_Block.get(),
                        ModBlocks.Enderium_Block.get(),
                        ModBlocks.Graphite_Block.get(),
                        ModBlocks.Iron_Compressed_Block.get(),
                        ModBlocks.Invar_Block.get(),
                        ModBlocks.Lead_Block.get(),
                        ModBlocks.Lead_Ore.get(),
                        ModBlocks.Lumium_Block.get(),
                        ModBlocks.Nickel_Block.get(),
                        ModBlocks.Nickel_Ore.get(),
                        ModBlocks.Osmium_Block.get(),
                        ModBlocks.Osmium_Ore.get(),
                        ModBlocks.Platinum_Block.get(),
                        ModBlocks.Platinum_Ore.get(),
                        ModBlocks.Quartz_Enriched_Iron_Block.get(),
                        ModBlocks.Raw_Aluminum_Block.get(),
                        ModBlocks.Raw_Lead_Block.get(),
                        ModBlocks.Raw_Nickel_Block.get(),
                        ModBlocks.Raw_Osmium_Block.get(),
                        ModBlocks.Raw_Platinum_Block.get(),
                        ModBlocks.Raw_Silver_Block.get(),
                        ModBlocks.Raw_Tin_Block.get(),
                        ModBlocks.Raw_Uranium_Block.get(),
                        ModBlocks.Raw_Zinc_Block.get(),
                        ModBlocks.Refined_Glowstone_Block.get(),
                        ModBlocks.Refined_Obsidian_Block.get(),
                        ModBlocks.Rose_Gold_Block.get(),
                        ModBlocks.Ruby_Block.get(),
                        ModBlocks.Ruby_Ore.get(),
                        ModBlocks.Sapphire_Block.get(),
                        ModBlocks.Sapphire_Ore.get(),
                        ModBlocks.Signalum_Block.get(),
                        ModBlocks.Silver_Block.get(),
                        ModBlocks.Silver_Ore.get(),
                        ModBlocks.Steel_Block.get(),
                        ModBlocks.Tin_Block.get(),
                        ModBlocks.Tin_Ore.get(),
                        ModBlocks.Uranium_Block.get(),
                        ModBlocks.Uranium_Ore.get(),
                        ModBlocks.Zinc_Block.get(),
                        ModBlocks.Zinc_Ore.get());

        this.tag(MINEABLE_WITH_HAMMER)
                .add(ModBlocks.Aluminum_Block.get(),
                        ModBlocks.Aluminum_Ore.get(),
                        ModBlocks.Andesite_Alloy_Block.get(),
                        ModBlocks.Apatite_Block.get(),
                        ModBlocks.Apatite_Ore.get(),
                        ModBlocks.Brass_Block.get(),
                        ModBlocks.Bronze_Block.get(),
                        ModBlocks.Cinnabar_Block.get(),
                        ModBlocks.Cinnabar_Ore.get(),
                        ModBlocks.Constantan_Block.get(),
                        ModBlocks.Deepslate_Aluminum_Ore.get(),
                        ModBlocks.Deepslate_Apatite_Ore.get(),
                        ModBlocks.Deepslate_Cinnabar_Ore.get(),
                        ModBlocks.Deepslate_Lead_Ore.get(),
                        ModBlocks.Deepslate_Nickel_Ore.get(),
                        ModBlocks.Deepslate_Osmium_Ore.get(),
                        ModBlocks.Deepslate_Platinum_Ore.get(),
                        ModBlocks.Deepslate_Ruby_Ore.get(),
                        ModBlocks.Deepslate_Sapphire_Ore.get(),
                        ModBlocks.Deepslate_Silver_Ore.get(),
                        ModBlocks.Deepslate_Tin_Ore.get(),
                        ModBlocks.Deepslate_Uranium_Ore.get(),
                        ModBlocks.Deepslate_Zinc_Ore.get(),
                        ModBlocks.Electrum_Block.get(),
                        ModBlocks.Enderium_Block.get(),
                        ModBlocks.Graphite_Block.get(),
                        ModBlocks.Iron_Compressed_Block.get(),
                        ModBlocks.Invar_Block.get(),
                        ModBlocks.Lead_Block.get(),
                        ModBlocks.Lead_Ore.get(),
                        ModBlocks.Lumium_Block.get(),
                        ModBlocks.Nickel_Block.get(),
                        ModBlocks.Nickel_Ore.get(),
                        ModBlocks.Osmium_Block.get(),
                        ModBlocks.Osmium_Ore.get(),
                        ModBlocks.Platinum_Block.get(),
                        ModBlocks.Platinum_Ore.get(),
                        ModBlocks.Quartz_Enriched_Iron_Block.get(),
                        ModBlocks.Raw_Aluminum_Block.get(),
                        ModBlocks.Raw_Lead_Block.get(),
                        ModBlocks.Raw_Nickel_Block.get(),
                        ModBlocks.Raw_Osmium_Block.get(),
                        ModBlocks.Raw_Platinum_Block.get(),
                        ModBlocks.Raw_Silver_Block.get(),
                        ModBlocks.Raw_Tin_Block.get(),
                        ModBlocks.Raw_Uranium_Block.get(),
                        ModBlocks.Raw_Zinc_Block.get(),
                        ModBlocks.Refined_Glowstone_Block.get(),
                        ModBlocks.Refined_Obsidian_Block.get(),
                        ModBlocks.Rose_Gold_Block.get(),
                        ModBlocks.Ruby_Block.get(),
                        ModBlocks.Ruby_Ore.get(),
                        ModBlocks.Sapphire_Block.get(),
                        ModBlocks.Sapphire_Ore.get(),
                        ModBlocks.Signalum_Block.get(),
                        ModBlocks.Silver_Block.get(),
                        ModBlocks.Silver_Ore.get(),
                        ModBlocks.Steel_Block.get(),
                        ModBlocks.Tin_Block.get(),
                        ModBlocks.Tin_Ore.get(),
                        ModBlocks.Uranium_Block.get(),
                        ModBlocks.Uranium_Ore.get(),
                        ModBlocks.Zinc_Block.get(),
                        ModBlocks.Zinc_Ore.get());

        this.tag(BlockTags.NEEDS_IRON_TOOL)
                .add(ModBlocks.Zinc_Ore.get(),
                        ModBlocks.Zinc_Block.get(),
                        ModBlocks.Raw_Zinc_Block.get(),
                        ModBlocks.Deepslate_Zinc_Ore.get(),
                        ModBlocks.Lead_Ore.get(),
                        ModBlocks.Lead_Block.get(),
                        ModBlocks.Raw_Lead_Block.get(),
                        ModBlocks.Deepslate_Lead_Ore.get(),
                        ModBlocks.Aluminum_Block.get(),
                        ModBlocks.Aluminum_Ore.get(),
                        ModBlocks.Raw_Aluminum_Block.get(),
                        ModBlocks.Deepslate_Aluminum_Ore.get(),
                        ModBlocks.Ruby_Ore.get(),
                        ModBlocks.Ruby_Block.get(),
                        ModBlocks.Deepslate_Ruby_Ore.get(),
                        ModBlocks.Sapphire_Block.get(),
                        ModBlocks.Sapphire_Ore.get(),
                        ModBlocks.Deepslate_Sapphire_Ore.get(),
                        ModBlocks.Apatite_Block.get(),
                        ModBlocks.Apatite_Ore.get(),
                        ModBlocks.Deepslate_Apatite_Ore.get(),
                        ModBlocks.Cinnabar_Ore.get(),
                        ModBlocks.Cinnabar_Block.get(),
                        ModBlocks.Deepslate_Cinnabar_Ore.get(),
                        ModBlocks.Bronze_Block.get(),
                        ModBlocks.Brass_Block.get(),
                        ModBlocks.Electrum_Block.get(),
                        ModBlocks.Steel_Block.get(),
                        ModBlocks.Andesite_Alloy_Block.get(),
                        ModBlocks.Rose_Gold_Block.get(),
                        ModBlocks.Graphite_Block.get());

        this.tag(BlockTags.NEEDS_DIAMOND_TOOL)
                .add(ModBlocks.Nickel_Block.get(),
                        ModBlocks.Nickel_Ore.get(),
                        ModBlocks.Raw_Nickel_Block.get(),
                        ModBlocks.Deepslate_Nickel_Ore.get(),
                        ModBlocks.Uranium_Ore.get(),
                        ModBlocks.Uranium_Block.get(),
                        ModBlocks.Raw_Uranium_Block.get(),
                        ModBlocks.Deepslate_Uranium_Ore.get(),
                        ModBlocks.Constantan_Block.get(),
                        ModBlocks.Iron_Compressed_Block.get(),
                        ModBlocks.Invar_Block.get(),
                        ModBlocks.Signalum_Block.get(),
                        ModBlocks.Enderium_Block.get());

        this.tag(BlockTags.NEEDS_STONE_TOOL)
                .add(ModBlocks.Silver_Ore.get(),
                        ModBlocks.Silver_Block.get(),
                        ModBlocks.Raw_Silver_Block.get(),
                        ModBlocks.Deepslate_Silver_Ore.get(),
                        ModBlocks.Tin_Block.get(),
                        ModBlocks.Tin_Ore.get(),
                        ModBlocks.Raw_Tin_Block.get(),
                        ModBlocks.Deepslate_Tin_Ore.get());

        this.tag(Tags.Blocks.NEEDS_NETHERITE_TOOL)
                .add(ModBlocks.Platinum_Block.get(),
                        ModBlocks.Platinum_Ore.get(),
                        ModBlocks.Raw_Platinum_Block.get(),
                        ModBlocks.Deepslate_Platinum_Ore.get(),
                        ModBlocks.Osmium_Block.get(),
                        ModBlocks.Osmium_Ore.get(),
                        ModBlocks.Raw_Osmium_Block.get(),
                        ModBlocks.Deepslate_Osmium_Ore.get(),
                        ModBlocks.Refined_Glowstone_Block.get(),
                        ModBlocks.Refined_Obsidian_Block.get());

        this.tag(ModTags.Blocks.STORAGE_BLOCKS)
                .add(
                        ModBlocks.Andesite_Alloy_Block.get(),
                        ModBlocks.Aluminum_Block.get(),
                        ModBlocks.Apatite_Block.get(),
                        ModBlocks.Brass_Block.get(),
                        ModBlocks.Bronze_Block.get(),
                        ModBlocks.Cinnabar_Block.get(),
                        ModBlocks.Constantan_Block.get(),
                        ModBlocks.Electrum_Block.get(),
                        ModBlocks.Enderium_Block.get(),
                        ModBlocks.Graphite_Block.get(),
                        ModBlocks.Invar_Block.get(),
                        ModBlocks.Lead_Block.get(),
                        ModBlocks.Lumium_Block.get(),
                        ModBlocks.Nickel_Block.get(),
                        ModBlocks.Signalum_Block.get(),
                        ModBlocks.Osmium_Block.get(),
                        ModBlocks.Platinum_Block.get(),
                        ModBlocks.Quartz_Enriched_Iron_Block.get(),
                        ModBlocks.Refined_Glowstone_Block.get(),
                        ModBlocks.Refined_Obsidian_Block.get(),
                        ModBlocks.Rose_Gold_Block.get(),
                        ModBlocks.Ruby_Block.get(),
                        ModBlocks.Sapphire_Block.get(),
                        ModBlocks.Silver_Block.get(),
                        ModBlocks.Steel_Block.get(),
                        ModBlocks.Tin_Block.get(),
                        ModBlocks.Uranium_Block.get(),
                        ModBlocks.Zinc_Block.get(),
                        ModBlocks.Raw_Aluminum_Block.get(),
                        ModBlocks.Raw_Lead_Block.get(),
                        ModBlocks.Raw_Nickel_Block.get(),
                        ModBlocks.Raw_Osmium_Block.get(),
                        ModBlocks.Raw_Platinum_Block.get(),
                        ModBlocks.Raw_Silver_Block.get(),
                        ModBlocks.Raw_Tin_Block.get(),
                        ModBlocks.Raw_Uranium_Block.get(),
                        ModBlocks.Raw_Zinc_Block.get());

        this.tag(ModTags.Blocks.ORES)
                .add(
                        ModBlocks.Aluminum_Ore.get(),
                        ModBlocks.Deepslate_Aluminum_Ore.get(),
                        ModBlocks.Apatite_Ore.get(),
                        ModBlocks.Deepslate_Apatite_Ore.get(),
                        ModBlocks.Cinnabar_Ore.get(),
                        ModBlocks.Deepslate_Cinnabar_Ore.get(),
                        ModBlocks.Lead_Ore.get(),
                        ModBlocks.Deepslate_Lead_Ore.get(),
                        ModBlocks.Nickel_Ore.get(),
                        ModBlocks.Deepslate_Nickel_Ore.get(),
                        ModBlocks.Osmium_Ore.get(),
                        ModBlocks.Deepslate_Osmium_Ore.get(),
                        ModBlocks.Platinum_Ore.get(),
                        ModBlocks.Deepslate_Platinum_Ore.get(),
                        ModBlocks.Ruby_Ore.get(),
                        ModBlocks.Deepslate_Ruby_Ore.get(),
                        ModBlocks.Sapphire_Ore.get(),
                        ModBlocks.Deepslate_Sapphire_Ore.get(),
                        ModBlocks.Silver_Ore.get(),
                        ModBlocks.Deepslate_Silver_Ore.get(),
                        ModBlocks.Tin_Ore.get(),
                        ModBlocks.Deepslate_Tin_Ore.get(),
                        ModBlocks.Uranium_Ore.get(),
                        ModBlocks.Deepslate_Uranium_Ore.get(),
                        ModBlocks.Zinc_Ore.get(),
                        ModBlocks.Deepslate_Zinc_Ore.get());
    }
}
